### ISSUE TITLE
Nice color picker but...

### ISSUE THREAD

**Issue by andretietz** [ItsPriyesh/chroma#1]
minsdk 14 or at least 15 would be nice, instead of 16.

dialog is extending alertdialog (support lib). A better approach would be to extending from DialogFragment. If you would do that you can rotate the device and still see the dialog

**Comment by ItsPriyesh** [comment]
Good point! I've converted it to a `DialogFragment` instead. Currently working on making it look better in landscape, and will cut another release after I've finished that.

**Comment by ItsPriyesh** [comment]
Version 1.0.1 extends `DialogFragment` and minSdk is now 14, closing this issue.
