### ISSUE TITLE
Alpha?

### ISSUE THREAD

**Issue by fedeamura** [ItsPriyesh/chroma#4]
Can you please add an alpha slider? :D

**Comment by MrBIMC** [comment]
I added it with my latest commit, let's await while @ItsPriyesh merges it.
If you want to use it right now, you can either clone my fork and use it as your local copy, or use my java-implementation of this lib(https://github.com/MrBIMC/VintageChroma)

**Comment by AmuraDeveloper** [comment]
Thanks MrBIMC!
:D

**Comment by ItsPriyesh** [comment]
ARGB color mode has been added to version 1.0.2.
